# Generated by Django 5.2.1 on 2025-06-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
