# Generated by Django 5.2.1 on 2025-05-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_api', '0002_disease_plant_solution_delete_diseasesolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='treatment_type',
            field=models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical')], max_length=100),
        ),
    ]
